NHS_SLUG_MAP = {
    '10 headache triggers': 'symptoms/headaches/10-headache-triggers',
    '10 ways to stop leaks': 'conditions/urinary-incontinence/10-ways-to-stop-leaks',
    'abdominal aortic aneurysm': 'conditions/abdominal-aortic-aneurysm',
    'about dementia': 'conditions/dementia/about-dementia',
    'acanthosis nigricans': 'conditions/acanthosis-nigricans',
    'achalasia': 'conditions/achalasia',
    'acid and chemical burns': 'conditions/acid-and-chemical-burns',
    'acne': 'conditions/acne',
    'acoustic neuroma': 'conditions/acoustic-neuroma',
    'acromegaly': 'conditions/acromegaly',
    'actinic keratoses': 'conditions/actinic-keratoses',
    'actinomycosis': 'conditions/actinomycosis',
    'activities': 'conditions/dementia/living-with-dementia/activities',
    'acute cholecystitis': 'conditions/acute-cholecystitis',
    'acute kidney injury': 'conditions/acute-kidney-injury',
    'acute lymphoblastic leukaemia': 'conditions/acute-lymphoblastic-leukaemia',
    'acute myeloid leukaemia': 'conditions/acute-myeloid-leukaemia',
    'acute pancreatitis': 'conditions/acute-pancreatitis',
    'acute respiratory distress syndrome': 'conditions/acute-respiratory-distress-syndrome',
    'addisons disease': 'conditions/addisons-disease',
    'adenomyosis': 'conditions/adenomyosis',
    'adhd adults': 'conditions/adhd-adults',
    'adhd children teenagers': 'conditions/adhd-children-teenagers',
    'adults': 'conditions/autism/signs/adults',
    'advice about medicines and medical appointments': 'conditions/autism/autism-and-everyday-life/advice-about-medicines-and-medical-appointments',
    'advice for life situations and events': 'mental-health/advice-for-life-situations-and-events',
    'advice for new parents': 'conditions/downs-syndrome/advice-for-new-parents',
    'advice for parents': 'mental-health/feelings-symptoms-behaviours/behaviours/eating-disorders/advice-for-parents',
    'afterwards': 'conditions/miscarriage/afterwards',
    'age related macular degeneration amd': 'conditions/age-related-macular-degeneration-amd',
    'agoraphobia': 'mental-health/conditions/agoraphobia',
    'albinism': 'conditions/albinism',
    'alcohol misuse': 'conditions/alcohol-misuse',
    'alcohol poisoning': 'conditions/alcohol-poisoning',
    'alcohol related liver disease arld': 'conditions/alcohol-related-liver-disease-arld',
    'allergic rhinitis': 'conditions/allergic-rhinitis',
    'allergies': 'conditions/allergies',
    'altitude sickness': 'conditions/altitude-sickness',
    'alzheimers disease': 'conditions/alzheimers-disease',
    'amyloidosis': 'conditions/amyloidosis',
    'anabolic steroid misuse': 'conditions/anabolic-steroid-misuse',
    'anal cancer': 'conditions/anal-cancer',
    'anal fissure': 'conditions/anal-fissure',
    'anal fistula': 'conditions/anal-fistula',
    'anal pain': 'symptoms/anal-pain',
    'anaphylaxis': 'conditions/anaphylaxis',
    'androgen insensitivity syndrome': 'conditions/androgen-insensitivity-syndrome',
    'angelman syndrome': 'conditions/angelman-syndrome',
    'anger': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/anger',
    'angina': 'conditions/angina',
    'angioedema': 'conditions/angioedema',
    'animal and human bites': 'conditions/animal-and-human-bites',
    'ankle pain': 'symptoms/foot-pain/ankle-pain',
    'ankylosing spondylitis': 'conditions/ankylosing-spondylitis',
    'annual health check smi': 'mental-health/social-care-and-your-rights/annual-health-check-smi',
    'annual health checks': 'conditions/learning-disabilities/annual-health-checks',
    'anorexia': 'mental-health/conditions/anorexia',
    'antiphospholipid syndrome': 'conditions/antiphospholipid-syndrome',
    'anxiety': 'mental-health/conditions/anxiety',
    'anxiety and children': 'mental-health/conditions/anxiety/anxiety-and-children',
    'anxiety disorder signs': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/anxiety-disorder-signs',
    'anxiety disorders in children': 'mental-health/children-and-young-adults/advice-for-parents/anxiety-disorders-in-children',
    'anxiety fear panic': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/anxiety-fear-panic',
    'anxiety in children': 'mental-health/children-and-young-adults/advice-for-parents/anxiety-in-children',
    'aphasia': 'conditions/aphasia',
    'appendicitis': 'conditions/appendicitis',
    'arrhythmia': 'conditions/arrhythmia',
    'arthritis': 'conditions/arthritis',
    'asbestosis': 'conditions/asbestosis',
    'aspergillosis': 'conditions/aspergillosis',
    'assessing your needs': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support/assessing-your-needs',
    'assessment and treatments': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/assessment-and-treatments',
    'assessments': 'conditions/autism/getting-diagnosed/assessments',
    'asthma': 'conditions/asthma',
    'astigmatism': 'conditions/astigmatism',
    'ataxia': 'conditions/ataxia',
    'atherosclerosis': 'conditions/atherosclerosis',
    'athletes foot': 'conditions/athletes-foot',
    'atopic eczema': 'conditions/atopic-eczema',
    'atrial fibrillation': 'conditions/atrial-fibrillation',
    'auditory processing disorder': 'conditions/auditory-processing-disorder',
    'autism': 'conditions/autism',
    'autism and everyday life': 'conditions/autism/autism-and-everyday-life',
    'autosomal dominant polycystic kidney disease adpkd': 'conditions/autosomal-dominant-polycystic-kidney-disease-adpkd',
    'autosomal recessive polycystic kidney disease arpkd': 'conditions/autosomal-recessive-polycystic-kidney-disease-arpkd',
    'back pain': 'conditions/back-pain',
    'bacterial vaginosis': 'conditions/bacterial-vaginosis',
    'bad breath': 'symptoms/bad-breath',
    'bakers cyst': 'conditions/bakers-cyst',
    'balanitis': 'conditions/balanitis',
    'bartholins cyst': 'conditions/bartholins-cyst',
    'bedbugs': 'conditions/bedbugs',
    'bedwetting': 'symptoms/bedwetting',
    'behaviour': 'conditions/dementia/living-with-dementia/behaviour',
    'behaviours': 'mental-health/feelings-symptoms-behaviours/behaviours',
    'behcets disease': 'conditions/behcets-disease',
    'bells palsy': 'conditions/bells-palsy',
    'bereavement': 'mental-health/advice-for-life-situations-and-events/bereavement',
    'bereavement and young people': 'mental-health/children-and-young-adults/help-for-teenagers-young-adults-and-students/bereavement-and-young-people',
    'bile duct cancer': 'conditions/bile-duct-cancer',
    'binge eating': 'mental-health/conditions/binge-eating',
    'bipolar disorder': 'mental-health/conditions/bipolar-disorder',
    'bird flu': 'conditions/bird-flu',
    'birthmarks': 'conditions/birthmarks',
    'black eye': 'conditions/black-eye',
    'bladder cancer': 'conditions/bladder-cancer',
    'bladder pain syndrome': 'conditions/bladder-pain-syndrome',
    'bladder stones': 'conditions/bladder-stones',
    'bleeding from the bottom rectal bleeding': 'symptoms/bleeding-from-the-bottom-rectal-bleeding',
    'blepharitis': 'conditions/blepharitis',
    'blisters': 'conditions/blisters',
    'bloating': 'symptoms/bloating',
    'blood in semen': 'symptoms/blood-in-semen',
    'blood in urine': 'symptoms/blood-in-urine',
    'blue skin or lips cyanosis': 'symptoms/blue-skin-or-lips-cyanosis',
    'blushing': 'symptoms/blushing',
    'body dysmorphia': 'mental-health/conditions/body-dysmorphia',
    'body odour bo': 'symptoms/body-odour-bo',
    'boils': 'conditions/boils',
    'bone cancer': 'conditions/bone-cancer',
    'bone cyst': 'conditions/bone-cyst',
    'borderline personality disorder': 'mental-health/conditions/borderline-personality-disorder',
    'botulism': 'conditions/botulism',
    'bowel cancer': 'conditions/bowel-cancer',
    'bowel incontinence': 'conditions/bowel-incontinence',
    'bowel polyps': 'conditions/bowel-polyps',
    'bowens disease': 'conditions/bowens-disease',
    'brain abscess': 'conditions/brain-abscess',
    'brain aneurysm': 'conditions/brain-aneurysm',
    'brain death': 'conditions/brain-death',
    'brain tumours': 'conditions/brain-tumours',
    'breast abscess': 'conditions/breast-abscess',
    'breast cancer in men': 'conditions/breast-cancer-in-men',
    'breast cancer in women': 'conditions/breast-cancer-in-women',
    'breast lump': 'symptoms/breast-lump',
    'breast pain': 'symptoms/breast-pain',
    'breath holding in babies and children': 'conditions/breath-holding-in-babies-and-children',
    'breathing exercises for stress': 'mental-health/self-help/guides-tools-and-activities/breathing-exercises-for-stress',
    'broken ankle': 'conditions/broken-ankle',
    'broken arm or wrist': 'conditions/broken-arm-or-wrist',
    'broken collarbone': 'conditions/broken-collarbone',
    'broken finger': 'conditions/broken-finger',
    'broken hip': 'conditions/broken-hip',
    'broken leg': 'conditions/broken-leg',
    'broken nose': 'conditions/broken-nose',
    'broken or bruised ribs': 'conditions/broken-or-bruised-ribs',
    'broken toe': 'conditions/broken-toe',
    'bronchiectasis': 'conditions/bronchiectasis',
    'bronchiolitis': 'conditions/bronchiolitis',
    'bronchitis': 'conditions/bronchitis',
    'brucellosis': 'conditions/brucellosis',
    'brugada syndrome': 'conditions/brugada-syndrome',
    'bulging eyes': 'symptoms/bulging-eyes',
    'bulimia': 'mental-health/conditions/bulimia',
    'bullous pemphigoid': 'conditions/bullous-pemphigoid',
    'bunions': 'conditions/bunions',
    'burns and scalds': 'conditions/burns-and-scalds',
    'bursitis': 'conditions/bursitis',
    'c difficile': 'conditions/c-difficile',
    'calcium': 'conditions/vitamins-and-minerals/calcium',
    'cancer': 'conditions/cancer',
    'carbon monoxide poisoning': 'conditions/carbon-monoxide-poisoning',
    'cardiomyopathy': 'conditions/cardiomyopathy',
    'cardiovascular disease': 'conditions/cardiovascular-disease',
    'care and support': 'conditions/dementia/care-and-support',
    'care homes': 'conditions/dementia/care-and-support/care-homes',
    'carpal tunnel syndrome': 'conditions/carpal-tunnel-syndrome',
    'carriers': 'conditions/sickle-cell-disease/carriers',
    'cataracts': 'conditions/cataracts',
    'catarrh': 'conditions/catarrh',
    'causes': 'conditions/ovarian-cyst/causes',
    'causes of breast cancer in men': 'conditions/breast-cancer-in-men/causes-of-breast-cancer-in-men',
    'causes of breast cancer in women': 'conditions/breast-cancer-in-women/causes-of-breast-cancer-in-women',
    'cavernoma': 'conditions/cavernoma',
    'cellulitis': 'conditions/cellulitis',
    'cerebral palsy': 'conditions/cerebral-palsy',
    'cervical cancer': 'conditions/cervical-cancer',
    'cervical spondylosis': 'conditions/cervical-spondylosis',
    'changing from child to adult care': 'conditions/autism/autism-and-everyday-life/changing-from-child-to-adult-care',
    'characteristics': 'conditions/noonan-syndrome/characteristics',
    'charcot marie tooth disease': 'conditions/charcot-marie-tooth-disease',
    'charles bonnet syndrome': 'conditions/charles-bonnet-syndrome',
    'chest infection': 'conditions/chest-infection',
    'chest pain': 'symptoms/chest-pain',
    'chiari malformation': 'conditions/chiari-malformation',
    'chickenpox': 'conditions/chickenpox',
    'chilblains': 'conditions/chilblains',
    'childhood cataracts': 'conditions/childhood-cataracts',
    'children': 'conditions/autism/signs/children',
    'children and bereavement': 'mental-health/children-and-young-adults/advice-for-parents/children-and-bereavement',
    'children and young adults': 'mental-health/children-and-young-adults',
    'children depressed signs': 'mental-health/children-and-young-adults/advice-for-parents/children-depressed-signs',
    'chipped broken or cracked tooth': 'conditions/chipped-broken-or-cracked-tooth',
    'chlamydia': 'conditions/chlamydia',
    'cholera': 'conditions/cholera',
    'cholesteatoma': 'conditions/cholesteatoma',
    'cholesterol levels': 'conditions/high-cholesterol/cholesterol-levels',
    'chronic fatigue syndrome cfs': 'conditions/chronic-fatigue-syndrome-cfs',
    'chronic lymphocytic leukaemia': 'conditions/chronic-lymphocytic-leukaemia',
    'chronic myeloid leukaemia': 'conditions/chronic-myeloid-leukaemia',
    'chronic obstructive pulmonary disease copd': 'conditions/chronic-obstructive-pulmonary-disease-copd',
    'chronic pancreatitis': 'conditions/chronic-pancreatitis',
    'chronic traumatic encephalopathy': 'conditions/chronic-traumatic-encephalopathy',
    'cirrhosis': 'conditions/cirrhosis',
    'claustrophobia': 'mental-health/conditions/claustrophobia',
    'cleft lip and palate': 'conditions/cleft-lip-and-palate',
    'club foot': 'conditions/club-foot',
    'cluster headaches': 'conditions/cluster-headaches',
    'coeliac disease': 'conditions/coeliac-disease',
    'cold sores': 'conditions/cold-sores',
    'colic': 'conditions/colic',
    'colour vision deficiency': 'conditions/colour-vision-deficiency',
    'common cold': 'conditions/common-cold',
    'communication': 'conditions/dementia/living-with-dementia/communication',
    'compartment syndrome': 'conditions/compartment-syndrome',
    'complex': 'mental-health/conditions/post-traumatic-stress-disorder-ptsd/complex',
    'complex regional pain syndrome': 'conditions/complex-regional-pain-syndrome',
    'complications': 'conditions/acute-pancreatitis/complications',
    'conditions': 'mental-health/conditions',
    'confusion': 'symptoms/confusion',
    'congenital heart disease': 'conditions/congenital-heart-disease',
    'conjunctivitis': 'conditions/conjunctivitis',
    'constipation': 'conditions/constipation',
    'contact dermatitis': 'conditions/contact-dermatitis',
    'cope with depression': 'mental-health/self-help/tips-and-support/cope-with-depression',
    'cope with your teenager': 'mental-health/children-and-young-adults/advice-for-parents/cope-with-your-teenager',
    'coping tips for women': 'symptoms/hair-loss/coping-tips-for-women',
    'coping with depression': 'mental-health/conditions/depression/coping-with-depression',
    'corns and calluses': 'conditions/corns-and-calluses',
    'coronary heart disease': 'conditions/coronary-heart-disease',
    'corticobasal degeneration': 'conditions/corticobasal-degeneration',
    'costochondritis': 'conditions/costochondritis',
    'cough': 'symptoms/cough',
    'coughing up blood': 'symptoms/coughing-up-blood',
    'covid 19': 'conditions/covid-19',
    'covid 19 symptoms and what to do': 'conditions/covid-19/covid-19-symptoms-and-what-to-do',
    'cradle cap': 'conditions/cradle-cap',
    'craniosynostosis': 'conditions/craniosynostosis',
    'creutzfeldt jakob disease cjd': 'conditions/creutzfeldt-jakob-disease-cjd',
    'crohns disease': 'conditions/crohns-disease',
    'croup': 'conditions/croup',
    'cure': 'conditions/dementia/about-dementia/cure',
    'cushings syndrome': 'conditions/cushings-syndrome',
    'cuts and grazes': 'conditions/cuts-and-grazes',
    'cyclical vomiting syndrome': 'conditions/cyclical-vomiting-syndrome',
    'cyclospora': 'conditions/cyclospora',
    'cyclothymia': 'mental-health/conditions/cyclothymia',
    'cystic fibrosis': 'conditions/cystic-fibrosis',
    'cystitis': 'conditions/cystitis',
    'cytomegalovirus cmv': 'conditions/cytomegalovirus-cmv',
    'dandruff': 'conditions/dandruff',
    'deafblindness': 'conditions/deafblindness',
    'deep vein thrombosis dvt': 'conditions/deep-vein-thrombosis-dvt',
    'dehydration': 'conditions/dehydration',
    'dementia': 'conditions/dementia',
    'dementia information service': 'conditions/dementia/care-and-support/dementia-information-service',
    'dementia with lewy bodies': 'conditions/dementia-with-lewy-bodies',
    'dengue': 'conditions/dengue',
    'dental abscess': 'conditions/dental-abscess',
    'depression': 'mental-health/conditions/depression',
    'depression in adults': 'mental-health/conditions/depression-in-adults',
    'detached retina retinal detachment': 'conditions/detached-retina-retinal-detachment',
    'developmental coordination disorder dyspraxia': 'conditions/developmental-coordination-disorder-dyspraxia',
    'developmental coordination disorder dyspraxia in adults': 'conditions/developmental-coordination-disorder-dyspraxia-in-adults',
    'developmental dysplasia of the hip': 'conditions/developmental-dysplasia-of-the-hip',
    'diabetes': 'conditions/diabetes',
    'diabetes insipidus': 'conditions/diabetes-insipidus',
    'diabetic ketoacidosis': 'conditions/diabetic-ketoacidosis',
    'diabetic retinopathy': 'conditions/diabetic-retinopathy',
    'diagnosis': 'conditions/pulmonary-hypertension/diagnosis',
    'diarrhoea and vomiting': 'symptoms/diarrhoea-and-vomiting',
    'diet lifestyle and medicines': 'conditions/irritable-bowel-syndrome-ibs/diet-lifestyle-and-medicines',
    'differences in sex development': 'conditions/differences-in-sex-development',
    'digeorge syndrome': 'conditions/digeorge-syndrome',
    'diphtheria': 'conditions/diphtheria',
    'discoid eczema': 'conditions/discoid-eczema',
    'dislocated kneecap': 'conditions/dislocated-kneecap',
    'dislocated shoulder': 'conditions/dislocated-shoulder',
    'dissociative disorders': 'mental-health/conditions/dissociative-disorders',
    'diverticular disease and diverticulitis': 'conditions/diverticular-disease-and-diverticulitis',
    'dizziness': 'symptoms/dizziness',
    'double vision': 'symptoms/double-vision',
    'downs syndrome': 'conditions/downs-syndrome',
    'dry eyes': 'symptoms/dry-eyes',
    'dry mouth': 'symptoms/dry-mouth',
    'dupuytrens contracture': 'conditions/dupuytrens-contracture',
    'dysarthria': 'conditions/dysarthria',
    'dysentery': 'conditions/dysentery',
    'dyslexia': 'conditions/dyslexia',
    'dystonia': 'conditions/dystonia',
    'ear infections': 'conditions/ear-infections',
    'earache': 'symptoms/earache',
    'early or delayed puberty': 'conditions/early-or-delayed-puberty',
    'early or premature menopause': 'conditions/early-or-premature-menopause',
    'earwax build up': 'conditions/earwax-build-up',
    'easy read and videos': 'conditions/autism/easy-read-and-videos',
    'eating disorders': 'mental-health/feelings-symptoms-behaviours/behaviours/eating-disorders',
    'ebola': 'conditions/ebola',
    'ectopic pregnancy': 'conditions/ectopic-pregnancy',
    'ectropion': 'conditions/ectropion',
    'edwards syndrome': 'conditions/edwards-syndrome',
    'ehlers danlos syndromes': 'conditions/ehlers-danlos-syndromes',
    'ejaculation problems': 'conditions/ejaculation-problems',
    'elbow and arm pain': 'symptoms/elbow-and-arm-pain',
    'encephalitis': 'conditions/encephalitis',
    'endocarditis': 'conditions/endocarditis',
    'endometriosis': 'conditions/endometriosis',
    'enlarged prostate': 'conditions/enlarged-prostate',
    'epidermolysis bullosa': 'conditions/epidermolysis-bullosa',
    'epididymitis': 'conditions/epididymitis',
    'epiglottitis': 'conditions/epiglottitis',
    'epilepsy': 'conditions/epilepsy',
    'erection problems erectile dysfunction': 'conditions/erection-problems-erectile-dysfunction',
    'erythema multiforme': 'conditions/erythema-multiforme',
    'erythema nodosum': 'conditions/erythema-nodosum',
    'erythrocytosis': 'conditions/erythrocytosis',
    'erythromelalgia': 'conditions/erythromelalgia',
    'excessive daytime sleepiness hypersomnia': 'conditions/excessive-daytime-sleepiness-hypersomnia',
    'excessive sweating hyperhidrosis': 'conditions/excessive-sweating-hyperhidrosis',
    'exercise for depression': 'mental-health/self-help/guides-tools-and-activities/exercise-for-depression',
    'eye cancer': 'conditions/eye-cancer',
    'eye injuries': 'conditions/eye-injuries',
    'eye pain': 'symptoms/eye-pain',
    'eyelid problems': 'symptoms/eyelid-problems',
    'fabricated or induced illness': 'mental-health/conditions/fabricated-or-induced-illness',
    'face blindness': 'conditions/face-blindness',
    'fainting': 'symptoms/fainting',
    'falls': 'conditions/falls',
    'febrile seizures': 'conditions/febrile-seizures',
    'feeling lonely': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/feeling-lonely',
    'feeling sick nausea': 'symptoms/feeling-sick-nausea',
    'feelings and symptoms': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms',
    'feelings symptoms behaviours': 'mental-health/feelings-symptoms-behaviours',
    'female genital mutilation fgm': 'conditions/female-genital-mutilation-fgm',
    'fertility in the menstrual cycle': 'conditions/periods/fertility-in-the-menstrual-cycle',
    'fetal alcohol spectrum disorder': 'conditions/fetal-alcohol-spectrum-disorder',
    'fever in adults': 'symptoms/fever-in-adults',
    'fever in children': 'symptoms/fever-in-children',
    'fibroids': 'conditions/fibroids',
    'fibromyalgia': 'conditions/fibromyalgia',
    'finances': 'conditions/dementia/care-and-support/finances',
    'finger pain': 'symptoms/hand-pain/finger-pain',
    'five steps to mental wellbeing': 'mental-health/self-help/guides-tools-and-activities/five-steps-to-mental-wellbeing',
    'flat feet': 'conditions/flat-feet',
    'flatulence': 'symptoms/flatulence',
    'floaters and flashes in the eyes': 'symptoms/floaters-and-flashes-in-the-eyes',
    'flu': 'conditions/flu',
    'food allergy': 'conditions/food-allergy',
    'food intolerance': 'conditions/food-intolerance',
    'food poisoning': 'conditions/food-poisoning',
    'foot drop': 'conditions/foot-drop',
    'foot pain': 'symptoms/foot-pain',
    'frontotemporal dementia': 'conditions/frontotemporal-dementia',
    'frostbite': 'conditions/frostbite',
    'frozen shoulder': 'conditions/frozen-shoulder',
    'fungal nail infection': 'conditions/fungal-nail-infection',
    'further help and support': 'conditions/irritable-bowel-syndrome-ibs/further-help-and-support',
    'gallbladder cancer': 'conditions/gallbladder-cancer',
    'gallstones': 'conditions/gallstones',
    'ganglion cyst': 'conditions/ganglion-cyst',
    'gangrene': 'conditions/gangrene',
    'gastritis': 'conditions/gastritis',
    'gastroparesis': 'conditions/gastroparesis',
    'gender dysphoria': 'conditions/gender-dysphoria',
    'generalised anxiety disorder gad': 'mental-health/conditions/generalised-anxiety-disorder-gad',
    'genital herpes': 'conditions/genital-herpes',
    'genital warts': 'conditions/genital-warts',
    'gestational diabetes': 'conditions/gestational-diabetes',
    'getting diagnosed': 'conditions/age-related-macular-degeneration-amd/getting-diagnosed',
    'getting help': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/getting-help',
    'getting help social care': 'mental-health/social-care-and-your-rights/getting-help-social-care',
    'getting tested': 'conditions/high-cholesterol/getting-tested',
    'giardiasis': 'conditions/giardiasis',
    'gilberts syndrome': 'conditions/gilberts-syndrome',
    'glandular fever': 'conditions/glandular-fever',
    'glaucoma': 'conditions/glaucoma',
    'glomerulonephritis': 'conditions/glomerulonephritis',
    'glue ear': 'conditions/glue-ear',
    'going into hospital': 'conditions/learning-disabilities/going-into-hospital',
    'goitre': 'conditions/goitre',
    'gonorrhoea': 'conditions/gonorrhoea',
    'gout': 'conditions/gout',
    'granuloma annulare': 'conditions/granuloma-annulare',
    'granulomatosis with polyangiitis': 'conditions/granulomatosis-with-polyangiitis',
    'grief bereavement loss': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/grief-bereavement-loss',
    'group b strep': 'conditions/group-b-strep',
    'growing pains': 'conditions/growing-pains',
    'guides tools and activities': 'mental-health/self-help/guides-tools-and-activities',
    'guillain barre syndrome': 'conditions/guillain-barre-syndrome',
    'gum disease': 'conditions/gum-disease',
    'gynaecomastia': 'conditions/gynaecomastia',
    'haemochromatosis': 'conditions/haemochromatosis',
    'haemophilia': 'conditions/haemophilia',
    'hair dye reactions': 'conditions/hair-dye-reactions',
    'hair loss': 'symptoms/hair-loss',
    'hallucinations hearing voices': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/hallucinations-hearing-voices',
    'hamstring injury': 'conditions/hamstring-injury',
    'hand foot mouth disease': 'conditions/hand-foot-mouth-disease',
    'hand pain': 'symptoms/hand-pain',
    'hay fever': 'conditions/hay-fever',
    'head injury and concussion': 'conditions/head-injury-and-concussion',
    'head lice and nits': 'conditions/head-lice-and-nits',
    'headaches': 'symptoms/headaches',
    'health anxiety': 'mental-health/conditions/health-anxiety',
    'hearing loss': 'conditions/hearing-loss',
    'heart attack': 'conditions/heart-attack',
    'heart block': 'conditions/heart-block',
    'heart failure': 'conditions/heart-failure',
    'heart palpitations': 'symptoms/heart-palpitations',
    'heart valve disease': 'conditions/heart-valve-disease',
    'heartburn and acid reflux': 'conditions/heartburn-and-acid-reflux',
    'heat exhaustion heatstroke': 'conditions/heat-exhaustion-heatstroke',
    'heat rash prickly heat': 'conditions/heat-rash-prickly-heat',
    'heavy periods': 'conditions/heavy-periods',
    'heel pain': 'symptoms/foot-pain/heel-pain',
    'help and support': 'conditions/bowel-cancer/help-and-support',
    'help and support for breast cancer in men': 'conditions/breast-cancer-in-men/help-and-support-for-breast-cancer-in-men',
    'help and support for breast cancer in women': 'conditions/breast-cancer-in-women/help-and-support-for-breast-cancer-in-women',
    'help for carers': 'mental-health/social-care-and-your-rights/help-for-carers',
    'help for day to day life': 'conditions/autism/autism-and-everyday-life/help-for-day-to-day-life',
    'help for families': 'conditions/autism/autism-and-everyday-life/help-for-families',
    'help for suicidal thoughts': 'mental-health/feelings-symptoms-behaviours/behaviours/help-for-suicidal-thoughts',
    'help for teenagers young adults and students': 'mental-health/children-and-young-adults/help-for-teenagers-young-adults-and-students',
    'help with behaviour': 'conditions/autism/autism-and-everyday-life/help-with-behaviour',
    'help your child beat exam stress': 'mental-health/children-and-young-adults/advice-for-parents/help-your-child-beat-exam-stress',
    'help your child with anger issues': 'mental-health/children-and-young-adults/advice-for-parents/help-your-child-with-anger-issues',
    'henoch schonlein purpura hsp': 'conditions/henoch-schonlein-purpura-hsp',
    'hepatitis': 'conditions/hepatitis',
    'hepatitis a': 'conditions/hepatitis-a',
    'hepatitis b': 'conditions/hepatitis-b',
    'hepatitis c': 'conditions/hepatitis-c',
    'hereditary haemorrahagic telangiectasia': 'conditions/hereditary-haemorrahagic-telangiectasia',
    'hereditary spastic paraplegia': 'conditions/hereditary-spastic-paraplegia',
    'hernia': 'conditions/hernia',
    'herpes simplex eye infections': 'conditions/herpes-simplex-eye-infections',
    'herpetic whitlow': 'conditions/herpetic-whitlow',
    'hiatus hernia': 'conditions/hiatus-hernia',
    'hib': 'conditions/hib',
    'hiccups': 'symptoms/hiccups',
    'hidradenitis suppurativa': 'conditions/hidradenitis-suppurativa',
    'high blood pressure': 'conditions/high-blood-pressure',
    'high blood sugar hyperglycaemia': 'conditions/high-blood-sugar-hyperglycaemia',
    'high cholesterol': 'conditions/high-cholesterol',
    'hip pain': 'symptoms/hip-pain',
    'hip pain children irritable hip': 'symptoms/hip-pain-children-irritable-hip',
    'hirschsprungs disease': 'conditions/hirschsprungs-disease',
    'hirsutism': 'symptoms/hirsutism',
    'hiv and aids': 'conditions/hiv-and-aids',
    'hives': 'conditions/hives',
    'hoarding disorder': 'mental-health/conditions/hoarding-disorder',
    'hodgkin lymphoma': 'conditions/hodgkin-lymphoma',
    'home environment': 'conditions/dementia/living-with-dementia/home-environment',
    'how get help and support': 'conditions/gender-dysphoria/how-get-help-and-support',
    'how tell someone about self harm': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/how-tell-someone-about-self-harm',
    'how to access mental health services': 'mental-health/social-care-and-your-rights/how-to-access-mental-health-services',
    'how to avoid catching and spreading covid 19': 'conditions/covid-19/how-to-avoid-catching-and-spreading-covid-19',
    'how to be happier': 'mental-health/self-help/tips-and-support/how-to-be-happier',
    'how to cope': 'mental-health/conditions/anxiety/how-to-cope',
    'how to cope with financial worries': 'mental-health/advice-for-life-situations-and-events/how-to-cope-with-financial-worries',
    'how to get diagnosed': 'conditions/autism/getting-diagnosed/how-to-get-diagnosed',
    'how to get support': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support',
    'how to help children and young people': 'conditions/downs-syndrome/how-to-help-children-and-young-people',
    'how to help someone else': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/how-to-help-someone-else',
    'how to help someone with depression': 'mental-health/advice-for-life-situations-and-events/how-to-help-someone-with-depression',
    'how to help someone with eating disorder': 'mental-health/advice-for-life-situations-and-events/how-to-help-someone-with-eating-disorder',
    'how to lower your cholesterol': 'conditions/high-cholesterol/how-to-lower-your-cholesterol',
    'human papilloma virus hpv': 'conditions/human-papilloma-virus-hpv',
    'huntingtons disease': 'conditions/huntingtons-disease',
    'hydrocephalus': 'conditions/hydrocephalus',
    'hydronephrosis': 'conditions/hydronephrosis',
    'hyperacusis': 'conditions/hyperacusis',
    'hyperparathyroidism': 'conditions/hyperparathyroidism',
    'hypoparathyroidism': 'conditions/hypoparathyroidism',
    'hypothermia': 'conditions/hypothermia',
    'ichthyosis': 'conditions/ichthyosis',
    'idiopathic pulmonary fibrosis': 'conditions/idiopathic-pulmonary-fibrosis',
    'impetigo': 'conditions/impetigo',
    'improving low mood': 'mental-health/conditions/depression/improving-low-mood',
    'incontinence products': 'conditions/urinary-incontinence/incontinence-products',
    'indigestion': 'conditions/indigestion',
    'infected piercings': 'conditions/infected-piercings',
    'infertility': 'conditions/infertility',
    'inflammatory bowel disease': 'conditions/inflammatory-bowel-disease',
    'ingrown hairs': 'conditions/ingrown-hairs',
    'ingrown toenail': 'conditions/ingrown-toenail',
    'insect bites and stings': 'conditions/insect-bites-and-stings',
    'insomnia': 'conditions/insomnia',
    'intracranial hypertension': 'conditions/intracranial-hypertension',
    'iodine': 'conditions/vitamins-and-minerals/iodine',
    'iron': 'conditions/vitamins-and-minerals/iron',
    'iron deficiency anaemia': 'conditions/iron-deficiency-anaemia',
    'irregular periods': 'symptoms/irregular-periods',
    'irritable bowel syndrome ibs': 'conditions/irritable-bowel-syndrome-ibs',
    'itchy anus': 'symptoms/itchy-anus',
    'itchy skin': 'symptoms/itchy-skin',
    'japanese encephalitis': 'conditions/japanese-encephalitis',
    'jaundice': 'conditions/jaundice',
    'jaundice newborn': 'conditions/jaundice-newborn',
    'jellyfish and other sea creature stings': 'conditions/jellyfish-and-other-sea-creature-stings',
    'jet lag': 'conditions/jet-lag',
    'joint hypermobility syndrome': 'conditions/joint-hypermobility-syndrome',
    'joint pain': 'symptoms/joint-pain',
    'just been diagnosed': 'conditions/dementia/symptoms-and-diagnosis/just-been-diagnosed',
    'kawasaki disease': 'conditions/kawasaki-disease',
    'keloid scars': 'conditions/keloid-scars',
    'keratosis pilaris': 'conditions/keratosis-pilaris',
    'kidney cancer': 'conditions/kidney-cancer',
    'kidney disease': 'conditions/kidney-disease',
    'kidney infection': 'conditions/kidney-infection',
    'kidney stones': 'conditions/kidney-stones',
    'klinefelters syndrome': 'conditions/klinefelters-syndrome',
    'knee pain': 'symptoms/knee-pain',
    'knock knees': 'conditions/knock-knees',
    'knocked out tooth': 'conditions/knocked-out-tooth',
    'kyphosis': 'conditions/kyphosis',
    'labial fusion': 'conditions/labial-fusion',
    'labyrinthitis': 'conditions/labyrinthitis',
    'lactose intolerance': 'conditions/lactose-intolerance',
    'lambert eaton myasthenic syndrome': 'conditions/lambert-eaton-myasthenic-syndrome',
    'laryngeal cancer': 'conditions/laryngeal-cancer',
    'laryngitis': 'conditions/laryngitis',
    'lazy eye': 'conditions/lazy-eye',
    'learning disabilities': 'conditions/learning-disabilities',
    'leg cramps': 'conditions/leg-cramps',
    'leg ulcer': 'conditions/leg-ulcer',
    'legal issues': 'conditions/dementia/care-and-support/legal-issues',
    'legionnaires disease': 'conditions/legionnaires-disease',
    'leptospirosis': 'conditions/leptospirosis',
    'leukoplakia': 'conditions/leukoplakia',
    'lichen planus': 'conditions/lichen-planus',
    'lichen sclerosus': 'conditions/lichen-sclerosus',
    'limp in children': 'symptoms/limp-in-children',
    'lipoedema': 'conditions/lipoedema',
    'lipoma': 'conditions/lipoma',
    'listeriosis': 'conditions/listeriosis',
    'liver cancer': 'conditions/liver-cancer',
    'liver disease': 'conditions/liver-disease',
    'living well': 'conditions/dementia/living-with-dementia/living-well',
    'living with': 'conditions/prader-willi-syndrome/living-with',
    'living with amd': 'conditions/age-related-macular-degeneration-amd/living-with-amd',
    'living with dementia': 'conditions/dementia/living-with-dementia',
    'loneliness in older people': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/loneliness-in-older-people',
    'loneliness in older people how to help': 'mental-health/advice-for-life-situations-and-events/loneliness-in-older-people-how-to-help',
    'long covid': 'conditions/long-covid',
    'long qt syndrome': 'conditions/long-qt-syndrome',
    'long sightedness': 'conditions/long-sightedness',
    'looking after someone': 'conditions/dementia/living-with-dementia/looking-after-someone',
    'loss of libido': 'symptoms/loss-of-libido',
    'lost or changed sense smell': 'symptoms/lost-or-changed-sense-smell',
    'low blood pressure hypotension': 'conditions/low-blood-pressure-hypotension',
    'low blood sugar hypoglycaemia': 'conditions/low-blood-sugar-hypoglycaemia',
    'low mood sadness depression': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/low-mood-sadness-depression',
    'low sperm count': 'conditions/low-sperm-count',
    'low white blood cell count': 'conditions/low-white-blood-cell-count',
    'lumps': 'symptoms/lumps',
    'lung cancer': 'conditions/lung-cancer',
    'lupus': 'conditions/lupus',
    'lyme disease': 'conditions/lyme-disease',
    'lymphoedema': 'conditions/lymphoedema',
    'macular hole': 'conditions/macular-hole',
    'malaria': 'conditions/malaria',
    'male menopause': 'conditions/male-menopause',
    'malignant brain tumour': 'conditions/malignant-brain-tumour',
    'mallet finger': 'conditions/mallet-finger',
    'malnutrition': 'conditions/malnutrition',
    'marfan syndrome': 'conditions/marfan-syndrome',
    'mastitis': 'conditions/mastitis',
    'mastocytosis': 'conditions/mastocytosis',
    'mastoiditis': 'conditions/mastoiditis',
    'measles': 'conditions/measles',
    'medically unexplained symptoms': 'conditions/medically-unexplained-symptoms',
    'medicines for high cholesterol': 'conditions/high-cholesterol/medicines-for-high-cholesterol',
    'melanoma skin cancer': 'conditions/melanoma-skin-cancer',
    'memory loss amnesia': 'symptoms/memory-loss-amnesia',
    'menieres disease': 'conditions/menieres-disease',
    'meningitis': 'conditions/meningitis',
    'meniscus tear': 'conditions/meniscus-tear',
    'menopause': 'conditions/menopause',
    'mental health': 'mental-health',
    'mental health act': 'mental-health/social-care-and-your-rights/mental-health-and-the-law/mental-health-act',
    'mental health act easy read': 'mental-health/social-care-and-your-rights/mental-health-and-the-law/mental-health-act-easy-read',
    'mental health and the law': 'mental-health/social-care-and-your-rights/mental-health-and-the-law',
    'mental health assessments': 'mental-health/social-care-and-your-rights/mental-health-assessments',
    'mental health charities': 'mental-health/children-and-young-adults/mental-health-support/mental-health-charities',
    'mental health services': 'mental-health/children-and-young-adults/mental-health-support/mental-health-services',
    'mental health support': 'mental-health/children-and-young-adults/mental-health-support',
    'mental health support if you are gay lesbian bisexual lgbtq': 'mental-health/advice-for-life-situations-and-events/mental-health-support-if-you-are-gay-lesbian-bisexual-lgbtq',
    'mental health treatments': 'mental-health/mental-health-treatments',
    'mental wellbeing audio guides': 'mental-health/self-help/guides-tools-and-activities/mental-wellbeing-audio-guides',
    'mesothelioma': 'conditions/mesothelioma',
    'metabolic syndrome': 'conditions/metabolic-syndrome',
    'metallic taste': 'symptoms/metallic-taste',
    'middle east respiratory syndrome mers': 'conditions/middle-east-respiratory-syndrome-mers',
    'migraine': 'conditions/migraine',
    'mindfulness': 'mental-health/self-help/tips-and-support/mindfulness',
    'miscarriage': 'conditions/miscarriage',
    'missed or late periods': 'symptoms/missed-or-late-periods',
    'molar pregnancy': 'conditions/molar-pregnancy',
    'moles': 'conditions/moles',
    'molluscum contagiosum': 'conditions/molluscum-contagiosum',
    'mortons neuroma': 'conditions/mortons-neuroma',
    'motion sickness': 'conditions/motion-sickness',
    'motor neurone disease': 'conditions/motor-neurone-disease',
    'mouth cancer': 'conditions/mouth-cancer',
    'mouth ulcers': 'conditions/mouth-ulcers',
    'moving on to adult services': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support/moving-on-to-adult-services',
    'mpox': 'conditions/mpox',
    'mrsa': 'conditions/mrsa',
    'mucositis': 'conditions/mucositis',
    'multiple sclerosis': 'conditions/multiple-sclerosis',
    'multiple system atrophy': 'conditions/multiple-system-atrophy',
    'mumps': 'conditions/mumps',
    'munchausen syndrome': 'mental-health/conditions/munchausen-syndrome',
    'muscular dystrophy': 'conditions/muscular-dystrophy',
    'myasthenia gravis': 'conditions/myasthenia-gravis',
    'myelodysplastic syndrome mds': 'conditions/myelodysplastic-syndrome-mds',
    'myeloma': 'conditions/myeloma',
    'myositis': 'conditions/myositis',
    'nail problems': 'symptoms/nail-problems',
    'narcolepsy': 'conditions/narcolepsy',
    'nasal and sinus cancer': 'conditions/nasal-and-sinus-cancer',
    'nasal polyps': 'conditions/nasal-polyps',
    'nasopharyngeal cancer': 'conditions/nasopharyngeal-cancer',
    'national fgm support clinics': 'conditions/female-genital-mutilation-fgm/national-fgm-support-clinics',
    'neck pain and stiff neck': 'symptoms/neck-pain-and-stiff-neck',
    'necrotising fasciitis': 'conditions/necrotising-fasciitis',
    'neonatal herpes': 'conditions/neonatal-herpes',
    'neonatal respiratory distress syndrome': 'conditions/neonatal-respiratory-distress-syndrome',
    'nephrotic syndrome': 'conditions/nephrotic-syndrome',
    'neurofibromatosis type 1': 'conditions/neurofibromatosis-type-1',
    'neurofibromatosis type 2': 'conditions/neurofibromatosis-type-2',
    'neuromyelitis optica': 'conditions/neuromyelitis-optica',
    'newly diagnosed': 'conditions/autism/newly-diagnosed',
    'night sweats': 'symptoms/night-sweats',
    'night terrors': 'conditions/night-terrors',
    'nipple discharge': 'symptoms/nipple-discharge',
    'non alcoholic fatty liver disease': 'conditions/non-alcoholic-fatty-liver-disease',
    'non allergic rhinitis': 'conditions/non-allergic-rhinitis',
    'non cancerous benign brain tumours': 'conditions/non-cancerous-benign-brain-tumours',
    'non hodgkin lymphoma': 'conditions/non-hodgkin-lymphoma',
    'non melanoma skin cancer': 'conditions/non-melanoma-skin-cancer',
    'noonan syndrome': 'conditions/noonan-syndrome',
    'norovirus': 'conditions/norovirus',
    'nosebleed': 'conditions/nosebleed',
    'obesity': 'conditions/obesity',
    'obsessive compulsive disorder ocd': 'mental-health/conditions/obsessive-compulsive-disorder-ocd',
    'oedema': 'conditions/oedema',
    'oesophageal atresia': 'conditions/oesophageal-atresia',
    'oesophageal cancer': 'conditions/oesophageal-cancer',
    'oral thrush mouth thrush': 'conditions/oral-thrush-mouth-thrush',
    'orf': 'conditions/orf',
    'osteoarthritis': 'conditions/osteoarthritis',
    'osteomyelitis': 'conditions/osteomyelitis',
    'osteophyte': 'conditions/osteophyte',
    'osteoporosis': 'conditions/osteoporosis',
    'other conditions': 'conditions/autism/other-conditions',
    'other health conditions': 'conditions/downs-syndrome/other-health-conditions',
    'others': 'conditions/vitamins-and-minerals/others',
    'otosclerosis': 'conditions/otosclerosis',
    'ovarian cancer': 'conditions/ovarian-cancer',
    'ovarian cyst': 'conditions/ovarian-cyst',
    'overactive thyroid hyperthyroidism': 'conditions/overactive-thyroid-hyperthyroidism',
    'overview': 'mental-health/conditions/anorexia/overview',
    'ovulation pain': 'symptoms/ovulation-pain',
    'pagets disease bone': 'conditions/pagets-disease-bone',
    'pagets disease nipple': 'conditions/pagets-disease-nipple',
    'pain in the back of the hand': 'symptoms/hand-pain/pain-in-the-back-of-the-hand',
    'pain in the ball of the foot': 'symptoms/foot-pain/pain-in-the-ball-of-the-foot',
    'pain in the bottom of the foot': 'symptoms/foot-pain/pain-in-the-bottom-of-the-foot',
    'pain in the palm of the hand': 'symptoms/hand-pain/pain-in-the-palm-of-the-hand',
    'pain in the top of the foot': 'symptoms/foot-pain/pain-in-the-top-of-the-foot',
    'palliative care': 'conditions/dementia/living-with-dementia/palliative-care',
    'pancreatic cancer': 'conditions/pancreatic-cancer',
    'panic disorder': 'mental-health/conditions/panic-disorder',
    'paralysis': 'symptoms/paralysis',
    'parkinsons disease': 'conditions/parkinsons-disease',
    'pataus syndrome': 'conditions/pataus-syndrome',
    'pelvic inflammatory disease pid': 'conditions/pelvic-inflammatory-disease-pid',
    'pelvic organ prolapse': 'conditions/pelvic-organ-prolapse',
    'pelvic pain': 'symptoms/pelvic-pain',
    'pemphigus vulgaris': 'conditions/pemphigus-vulgaris',
    'penile cancer': 'conditions/penile-cancer',
    'penis lumps and spots': 'symptoms/penis-lumps-and-spots',
    'perforated eardrum': 'conditions/perforated-eardrum',
    'pericarditis': 'conditions/pericarditis',
    'period pain': 'symptoms/period-pain',
    'period problems': 'conditions/periods/period-problems',
    'periods': 'conditions/periods',
    'peripheral arterial disease pad': 'conditions/peripheral-arterial-disease-pad',
    'peripheral neuropathy': 'conditions/peripheral-neuropathy',
    'peritonitis': 'conditions/peritonitis',
    'personality disorder': 'mental-health/conditions/personality-disorder',
    'peyronies disease': 'conditions/peyronies-disease',
    'phaeochromocytoma': 'conditions/phaeochromocytoma',
    'phimosis': 'conditions/phimosis',
    'phlebitis': 'conditions/phlebitis',
    'phobias': 'mental-health/conditions/phobias',
    'piles haemorrhoids': 'conditions/piles-haemorrhoids',
    'pilonidal sinus': 'conditions/pilonidal-sinus',
    'pins and needles': 'symptoms/pins-and-needles',
    'pip implants': 'conditions/pip-implants',
    'pityriasis rosea': 'conditions/pityriasis-rosea',
    'pityriasis versicolor': 'conditions/pityriasis-versicolor',
    'plagiocephaly brachycephaly': 'conditions/plagiocephaly-brachycephaly',
    'plantar fasciitis': 'conditions/plantar-fasciitis',
    'pleurisy': 'conditions/pleurisy',
    'pneumonia': 'conditions/pneumonia',
    'poisoning': 'conditions/poisoning',
    'polio': 'conditions/polio',
    'polycystic ovary syndrome pcos': 'conditions/polycystic-ovary-syndrome-pcos',
    'polyhydramnios': 'conditions/polyhydramnios',
    'polymorphic light eruption': 'conditions/polymorphic-light-eruption',
    'polymyalgia rheumatica': 'conditions/polymyalgia-rheumatica',
    'pompholyx': 'conditions/pompholyx',
    'post herpetic neuralgia': 'conditions/post-herpetic-neuralgia',
    'post menopausal bleeding': 'symptoms/post-menopausal-bleeding',
    'post natal depression': 'mental-health/conditions/post-natal-depression',
    'post partum psychosis': 'mental-health/conditions/post-partum-psychosis',
    'post traumatic stress disorder ptsd': 'mental-health/conditions/post-traumatic-stress-disorder-ptsd',
    'postural tachycardia syndrome': 'conditions/postural-tachycardia-syndrome',
    'prader willi syndrome': 'conditions/prader-willi-syndrome',
    'pre eclampsia': 'conditions/pre-eclampsia',
    'pre menstrual syndrome': 'conditions/pre-menstrual-syndrome',
    'pressure sores': 'conditions/pressure-sores',
    'prevention': 'conditions/dementia/about-dementia/prevention',
    'priapism painful erections': 'symptoms/priapism-painful-erections',
    'primary biliary cholangitis pbc': 'conditions/primary-biliary-cholangitis-pbc',
    'problems swallowing pills': 'conditions/problems-swallowing-pills',
    'progressive supranuclear palsy psp': 'conditions/progressive-supranuclear-palsy-psp',
    'prostate cancer': 'conditions/prostate-cancer',
    'prostatitis': 'conditions/prostatitis',
    'psoriasis': 'conditions/psoriasis',
    'psoriatic arthritis': 'conditions/psoriatic-arthritis',
    'psychosis': 'mental-health/conditions/psychosis',
    'psychotic depression': 'mental-health/conditions/psychotic-depression',
    'pubic lice': 'conditions/pubic-lice',
    'pudendal neuralgia': 'conditions/pudendal-neuralgia',
    'pulmonary embolism': 'conditions/pulmonary-embolism',
    'pulmonary hypertension': 'conditions/pulmonary-hypertension',
    'pyoderma gangrenosum': 'conditions/pyoderma-gangrenosum',
    'q fever': 'conditions/q-fever',
    'rabies': 'conditions/rabies',
    'raise low self esteem': 'mental-health/self-help/tips-and-support/raise-low-self-esteem',
    'rashes babies and children': 'symptoms/rashes-babies-and-children',
    'raynauds': 'conditions/raynauds',
    'reactive arthritis': 'conditions/reactive-arthritis',
    'receiving support': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support/receiving-support',
    'recovery': 'conditions/coronary-heart-disease/recovery',
    'red eye': 'symptoms/red-eye',
    'reflux in babies': 'conditions/reflux-in-babies',
    'relationships': 'conditions/dementia/living-with-dementia/relationships',
    'repetitive strain injury rsi': 'conditions/repetitive-strain-injury-rsi',
    'respiratory syncytial virus rsv': 'conditions/respiratory-syncytial-virus-rsv',
    'respiratory tract infection': 'conditions/respiratory-tract-infection',
    'restless legs syndrome': 'conditions/restless-legs-syndrome',
    'restricted growth': 'conditions/restricted-growth',
    'retinal migraine': 'conditions/retinal-migraine',
    'retinoblastoma': 'conditions/retinoblastoma',
    'rett syndrome': 'conditions/rett-syndrome',
    'return to work after mental health issues': 'mental-health/advice-for-life-situations-and-events/return-to-work-after-mental-health-issues',
    'reyes syndrome': 'conditions/reyes-syndrome',
    'rhesus disease': 'conditions/rhesus-disease',
    'rheumatic fever': 'conditions/rheumatic-fever',
    'rheumatoid arthritis': 'conditions/rheumatoid-arthritis',
    'rickets and osteomalacia': 'conditions/rickets-and-osteomalacia',
    'ringworm': 'conditions/ringworm',
    'risks': 'conditions/alcohol-misuse/risks',
    'rosacea': 'conditions/rosacea',
    'roseola': 'conditions/roseola',
    'rubella': 'conditions/rubella',
    'salivary gland stones': 'conditions/salivary-gland-stones',
    'sarcoidosis': 'conditions/sarcoidosis',
    'scabies': 'conditions/scabies',
    'scarlet fever': 'conditions/scarlet-fever',
    'scars': 'conditions/scars',
    'schistosomiasis': 'conditions/schistosomiasis',
    'schizophrenia': 'mental-health/conditions/schizophrenia',
    'school': 'conditions/autism/autism-and-everyday-life/school',
    'sciatica': 'conditions/sciatica',
    'scleroderma': 'conditions/scleroderma',
    'scoliosis': 'conditions/scoliosis',
    'scurvy': 'conditions/scurvy',
    'seasonal affective disorder sad': 'mental-health/conditions/seasonal-affective-disorder-sad',
    'selective mutism': 'mental-health/conditions/selective-mutism',
    'self harm': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm',
    'self help': 'conditions/fibromyalgia/self-help',
    'sepsis': 'conditions/sepsis',
    'septic arthritis': 'conditions/septic-arthritis',
    'sexually transmitted infections stis': 'conditions/sexually-transmitted-infections-stis',
    'shin splints': 'conditions/shin-splints',
    'shingles': 'conditions/shingles',
    'short sightedness': 'conditions/short-sightedness',
    'shortness of breath': 'symptoms/shortness-of-breath',
    'shoulder impingement syndrome': 'conditions/shoulder-impingement-syndrome',
    'shoulder pain': 'symptoms/shoulder-pain',
    'sick building syndrome': 'conditions/sick-building-syndrome',
    'sickle cell disease': 'conditions/sickle-cell-disease',
    'signs': 'mental-health/conditions/fabricated-or-induced-illness/signs',
    'silicosis': 'conditions/silicosis',
    'sinusitis sinus infection': 'conditions/sinusitis-sinus-infection',
    'sjogrens syndrome': 'conditions/sjogrens-syndrome',
    'skin abscess': 'conditions/skin-abscess',
    'skin cyst': 'conditions/skin-cyst',
    'skin picking disorder': 'mental-health/conditions/skin-picking-disorder',
    'skin tags': 'conditions/skin-tags',
    'slapped cheek syndrome': 'conditions/slapped-cheek-syndrome',
    'sleep apnoea': 'conditions/sleep-apnoea',
    'sleep paralysis': 'conditions/sleep-paralysis',
    'sleepwalking': 'conditions/sleepwalking',
    'slipped disc': 'conditions/slipped-disc',
    'smelly feet': 'symptoms/smelly-feet',
    'smelly urine': 'symptoms/smelly-urine',
    'snake bites': 'conditions/snake-bites',
    'snoring': 'symptoms/snoring',
    'social anxiety': 'mental-health/conditions/social-anxiety',
    'social care and your rights': 'mental-health/social-care-and-your-rights',
    'social services and the nhs': 'conditions/dementia/care-and-support/social-services-and-the-nhs',
    'soft tissue sarcoma': 'conditions/soft-tissue-sarcoma',
    'soiling child pooing their pants': 'symptoms/soiling-child-pooing-their-pants',
    'sore or dry lips': 'symptoms/sore-or-dry-lips',
    'sore or white tongue': 'symptoms/sore-or-white-tongue',
    'sore throat': 'symptoms/sore-throat',
    'spina bifida': 'conditions/spina-bifida',
    'spinal muscular atrophy sma': 'conditions/spinal-muscular-atrophy-sma',
    'spondylolisthesis': 'conditions/spondylolisthesis',
    'sprains and strains': 'conditions/sprains-and-strains',
    'squint': 'conditions/squint',
    'stammering': 'conditions/stammering',
    'staphylococcal infections': 'conditions/staphylococcal-infections',
    'starting periods': 'conditions/periods/starting-periods',
    'staying independent': 'conditions/dementia/living-with-dementia/staying-independent',
    'stevens johnson syndrome': 'conditions/stevens-johnson-syndrome',
    'stillbirth': 'conditions/stillbirth',
    'stomach ache': 'symptoms/stomach-ache',
    'stomach cancer': 'conditions/stomach-cancer',
    'stomach ulcer': 'conditions/stomach-ulcer',
    'strep a': 'conditions/strep-a',
    'stress': 'mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/stress',
    'stretch marks': 'conditions/stretch-marks',
    'stroke': 'conditions/stroke',
    'student mental health counselling': 'mental-health/children-and-young-adults/help-for-teenagers-young-adults-and-students/student-mental-health-counselling',
    'student stress self help tips': 'mental-health/children-and-young-adults/help-for-teenagers-young-adults-and-students/student-stress-self-help-tips',
    'stye': 'conditions/stye',
    'subarachnoid haemorrhage': 'conditions/subarachnoid-haemorrhage',
    'subdural haematoma': 'conditions/subdural-haematoma',
    'success': 'conditions/dementia/care-and-support/dementia-information-service/success',
    'sudden infant death syndrome sids': 'conditions/sudden-infant-death-syndrome-sids',
    'sunburn': 'conditions/sunburn',
    'support': 'conditions/autism/support',
    'support for adults': 'conditions/downs-syndrome/support-for-adults',
    'support for families and carers': 'conditions/downs-syndrome/support-for-families-and-carers',
    'support for workplace bullying': 'mental-health/advice-for-life-situations-and-events/support-for-workplace-bullying',
    'support groups': 'mental-health/conditions/depression-in-adults/support-groups',
    'supporting a child or young person': 'mental-health/children-and-young-adults/mental-health-support/supporting-a-child-or-young-person',
    'supraventricular tachycardia svt': 'conditions/supraventricular-tachycardia-svt',
    'surgery': 'conditions/squint/surgery',
    'swallowing problems dysphagia': 'symptoms/swallowing-problems-dysphagia',
    'swollen arms and hands oedema': 'conditions/swollen-arms-and-hands-oedema',
    'swollen glands': 'symptoms/swollen-glands',
    'symptoms': 'conditions/stroke/symptoms',
    'symptoms and diagnosis': 'conditions/dementia/symptoms-and-diagnosis',
    'symptoms of breast cancer in men': 'conditions/breast-cancer-in-men/symptoms-of-breast-cancer-in-men',
    'symptoms of breast cancer in women': 'conditions/breast-cancer-in-women/symptoms-of-breast-cancer-in-women',
    'syphilis': 'conditions/syphilis',
    'tailbone coccyx pain': 'conditions/tailbone-coccyx-pain',
    'talk to children about feelings': 'mental-health/children-and-young-adults/advice-for-parents/talk-to-children-about-feelings',
    'talk to your teenager': 'mental-health/children-and-young-adults/advice-for-parents/talk-to-your-teenager',
    'teen aggression and arguments': 'mental-health/children-and-young-adults/advice-for-parents/teen-aggression-and-arguments',
    'teeth grinding': 'symptoms/teeth-grinding',
    'temporal arteritis': 'conditions/temporal-arteritis',
    'temporomandibular disorder tmd': 'conditions/temporomandibular-disorder-tmd',
    'tendonitis': 'conditions/tendonitis',
    'tennis elbow': 'conditions/tennis-elbow',
    'tension headaches': 'conditions/tension-headaches',
    'testicle lumps and swellings': 'symptoms/testicle-lumps-and-swellings',
    'testicle pain': 'symptoms/testicle-pain',
    'testicular cancer': 'conditions/testicular-cancer',
    'tests': 'conditions/hodgkin-lymphoma/tests',
    'tests and next steps': 'conditions/non-melanoma-skin-cancer/tests-and-next-steps',
    'tests and next steps for breast cancer in men': 'conditions/breast-cancer-in-men/tests-and-next-steps-for-breast-cancer-in-men',
    'tests and next steps for breast cancer in women': 'conditions/breast-cancer-in-women/tests-and-next-steps-for-breast-cancer-in-women',
    'tetanus': 'conditions/tetanus',
    'thalassaemia': 'conditions/thalassaemia',
    'things you can do': 'conditions/menopause/things-you-can-do',
    'thirst': 'symptoms/thirst',
    'thoracic outlet syndrome': 'conditions/thoracic-outlet-syndrome',
    'threadworms': 'conditions/threadworms',
    'thrombophilia': 'conditions/thrombophilia',
    'thrush in men and women': 'conditions/thrush-in-men-and-women',
    'thumb pain': 'symptoms/hand-pain/thumb-pain',
    'thyroid cancer': 'conditions/thyroid-cancer',
    'tick borne encephalitis': 'conditions/tick-borne-encephalitis',
    'tics': 'conditions/tics',
    'tinnitus': 'conditions/tinnitus',
    'tips and support': 'mental-health/self-help/tips-and-support',
    'tips on preparing for exams': 'mental-health/children-and-young-adults/help-for-teenagers-young-adults-and-students/tips-on-preparing-for-exams',
    'tips to reduce stress': 'mental-health/self-help/guides-tools-and-activities/tips-to-reduce-stress',
    'tiredness and fatigue': 'symptoms/tiredness-and-fatigue',
    'toe pain': 'symptoms/foot-pain/toe-pain',
    'tongue tie': 'conditions/tongue-tie',
    'tonsillitis': 'conditions/tonsillitis',
    'tooth decay': 'conditions/tooth-decay',
    'toothache': 'symptoms/toothache',
    'tourette syndrome': 'conditions/tourette-syndrome',
    'toxic shock syndrome': 'conditions/toxic-shock-syndrome',
    'toxocariasis': 'conditions/toxocariasis',
    'toxoplasmosis': 'conditions/toxoplasmosis',
    'transient ischaemic attack tia': 'conditions/transient-ischaemic-attack-tia',
    'treatment': 'conditions/type-2-diabetes/treatment',
    'treatment and recovery': 'conditions/sepsis/treatment-and-recovery',
    'treatment for breast cancer in men': 'conditions/breast-cancer-in-men/treatment-for-breast-cancer-in-men',
    'treatment for breast cancer in women': 'conditions/breast-cancer-in-women/treatment-for-breast-cancer-in-women',
    'treatment in adults': 'conditions/scoliosis/treatment-in-adults',
    'treatment in children': 'conditions/scoliosis/treatment-in-children',
    'treatments for covid 19': 'conditions/covid-19/treatments-for-covid-19',
    'treatments that are not recommended for autism': 'conditions/autism/autism-and-everyday-life/treatments-that-are-not-recommended-for-autism',
    'tremor or shaking hands': 'symptoms/tremor-or-shaking-hands',
    'trichomoniasis': 'conditions/trichomoniasis',
    'trichotillomania': 'mental-health/conditions/trichotillomania',
    'trigeminal neuralgia': 'conditions/trigeminal-neuralgia',
    'trigger finger': 'conditions/trigger-finger',
    'tuberculosis tb': 'conditions/tuberculosis-tb',
    'turner syndrome': 'conditions/turner-syndrome',
    'twitching eyes and muscles': 'symptoms/twitching-eyes-and-muscles',
    'type 1 diabetes': 'conditions/type-1-diabetes',
    'type 2 diabetes': 'conditions/type-2-diabetes',
    'types': 'conditions/congenital-heart-disease/types',
    'types of anxiety': 'mental-health/conditions/anxiety/types-of-anxiety',
    'types of depression': 'mental-health/conditions/depression/types-of-depression',
    'typhoid fever': 'conditions/typhoid-fever',
    'typhus': 'conditions/typhus',
    'ulcerative colitis': 'conditions/ulcerative-colitis',
    'underactive thyroid hypothyroidism': 'conditions/underactive-thyroid-hypothyroidism',
    'undescended testicles': 'conditions/undescended-testicles',
    'unintentional weight loss': 'symptoms/unintentional-weight-loss',
    'urethritis': 'conditions/urethritis',
    'urinary incontinence': 'conditions/urinary-incontinence',
    'urinary tract infections utis': 'conditions/urinary-tract-infections-utis',
    'uveitis': 'conditions/uveitis',
    'vaccination': 'conditions/rabies/vaccination',
    'vaginal bleeding between periods or after sex': 'symptoms/vaginal-bleeding-between-periods-or-after-sex',
    'vaginal cancer': 'conditions/vaginal-cancer',
    'vaginal discharge': 'symptoms/vaginal-discharge',
    'vaginal dryness': 'symptoms/vaginal-dryness',
    'vaginismus': 'conditions/vaginismus',
    'vaginitis': 'conditions/vaginitis',
    'varicose eczema': 'conditions/varicose-eczema',
    'varicose veins': 'conditions/varicose-veins',
    'vascular dementia': 'conditions/vascular-dementia',
    'vasculitis': 'conditions/vasculitis',
    'vertigo': 'conditions/vertigo',
    'vision loss': 'conditions/vision-loss',
    'vitamin a': 'conditions/vitamins-and-minerals/vitamin-a',
    'vitamin b': 'conditions/vitamins-and-minerals/vitamin-b',
    'vitamin b12 or folate deficiency anaemia': 'conditions/vitamin-b12-or-folate-deficiency-anaemia',
    'vitamin c': 'conditions/vitamins-and-minerals/vitamin-c',
    'vitamin d': 'conditions/vitamins-and-minerals/vitamin-d',
    'vitamin e': 'conditions/vitamins-and-minerals/vitamin-e',
    'vitamin k': 'conditions/vitamins-and-minerals/vitamin-k',
    'vitamins and minerals': 'conditions/vitamins-and-minerals',
    'vitiligo': 'conditions/vitiligo',
    'vomiting blood': 'symptoms/vomiting-blood',
    'von willebrand disease': 'conditions/von-willebrand-disease',
    'vulval cancer': 'conditions/vulval-cancer',
    'vulvodynia': 'conditions/vulvodynia',
    'waiting for support': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support/waiting-for-support',
    'warts and verrucas': 'conditions/warts-and-verrucas',
    'watering eyes': 'symptoms/watering-eyes',
    'ways help avoid self harm': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/ways-help-avoid-self-harm',
    'what happens': 'conditions/miscarriage/what-happens',
    'what is a malignant brain tumour': 'conditions/malignant-brain-tumour/what-is-a-malignant-brain-tumour',
    'what is acute lymphoblastic leukaemia': 'conditions/acute-lymphoblastic-leukaemia/what-is-acute-lymphoblastic-leukaemia',
    'what is anal cancer': 'conditions/anal-cancer/what-is-anal-cancer',
    'what is autism': 'conditions/autism/what-is-autism',
    'what is bile duct cancer': 'conditions/bile-duct-cancer/what-is-bile-duct-cancer',
    'what is bladder cancer': 'conditions/bladder-cancer/what-is-bladder-cancer',
    'what is bone cancer': 'conditions/bone-cancer/what-is-bone-cancer',
    'what is bowel cancer': 'conditions/bowel-cancer/what-is-bowel-cancer',
    'what is breast cancer in men': 'conditions/breast-cancer-in-men/what-is-breast-cancer-in-men',
    'what is breast cancer in women': 'conditions/breast-cancer-in-women/what-is-breast-cancer-in-women',
    'what is cervical cancer': 'conditions/cervical-cancer/what-is-cervical-cancer',
    'what is cml': 'conditions/chronic-myeloid-leukaemia/what-is-cml',
    'what is dementia': 'conditions/dementia/about-dementia/what-is-dementia',
    'what is gallbladder cancer': 'conditions/gallbladder-cancer/what-is-gallbladder-cancer',
    'what is hodgkin lymphoma': 'conditions/hodgkin-lymphoma/what-is-hodgkin-lymphoma',
    'what is ibs': 'conditions/irritable-bowel-syndrome-ibs/what-is-ibs',
    'what is it': 'conditions/nasal-and-sinus-cancer/what-is-it',
    'what is kidney cancer': 'conditions/kidney-cancer/what-is-kidney-cancer',
    'what is laryngeal cancer': 'conditions/laryngeal-cancer/what-is-laryngeal-cancer',
    'what is liver cancer': 'conditions/liver-cancer/what-is-liver-cancer',
    'what is mds': 'conditions/myelodysplastic-syndrome-mds/what-is-mds',
    'what is mouth cancer': 'conditions/mouth-cancer/what-is-mouth-cancer',
    'what is myeloma': 'conditions/myeloma/what-is-myeloma',
    'what is non melanoma skin cancer': 'conditions/non-melanoma-skin-cancer/what-is-non-melanoma-skin-cancer',
    'what is oesophageal cancer': 'conditions/oesophageal-cancer/what-is-oesophageal-cancer',
    'what is pancreatic cancer': 'conditions/pancreatic-cancer/what-is-pancreatic-cancer',
    'what is penile cancer': 'conditions/penile-cancer/what-is-penile-cancer',
    'what is prostate cancer': 'conditions/prostate-cancer/what-is-prostate-cancer',
    'what is retinoblastoma': 'conditions/retinoblastoma/what-is-retinoblastoma',
    'what is soft tissue sarcoma': 'conditions/soft-tissue-sarcoma/what-is-soft-tissue-sarcoma',
    'what is testicular cancer': 'conditions/testicular-cancer/what-is-testicular-cancer',
    'what is thyroid cancer': 'conditions/thyroid-cancer/what-is-thyroid-cancer',
    'what is type 1 diabetes': 'conditions/type-1-diabetes/what-is-type-1-diabetes',
    'what is type 2 diabetes': 'conditions/type-2-diabetes/what-is-type-2-diabetes',
    'what is vulval cancer': 'conditions/vulval-cancer/what-is-vulval-cancer',
    'what to do if someone has a seizure fit': 'symptoms/what-to-do-if-someone-has-a-seizure-fit',
    'where find help and support': 'conditions/stomach-cancer/where-find-help-and-support',
    'where to find help and support': 'conditions/anal-cancer/where-to-find-help-and-support',
    'where to get support': 'mental-health/children-and-young-adults/mental-health-support/how-to-get-support/where-to-get-support',
    'whiplash': 'conditions/whiplash',
    'who can get it': 'conditions/sepsis/who-can-get-it',
    'whooping cough': 'conditions/whooping-cough',
    'why people self harm': 'mental-health/feelings-symptoms-behaviours/behaviours/self-harm/why-people-self-harm',
    'wolff parkinson white syndrome': 'conditions/wolff-parkinson-white-syndrome',
    'womb cancer': 'conditions/womb-cancer',
    'worms in humans': 'symptoms/worms-in-humans',
    'worried about your teenager': 'mental-health/children-and-young-adults/advice-for-parents/worried-about-your-teenager',
    'worried someone has dementia': 'conditions/dementia/about-dementia/worried-someone-has-dementia',
    'wrist pain': 'symptoms/hand-pain/wrist-pain',
    'yellow fever': 'conditions/yellow-fever',
    'zika': 'conditions/zika',
}
